AMQP_URI: amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_HOST}:${RABBIT_PORT}/
SENTRY:
  DSN: http://${SENTRY_PUBLIC_KEY}@${SENTRY_HOST}:${SENTRY_PORT}/1
  CLIENT_CONFIG:
    site: "Nameko Woocommerce Service"

DB_URIS:
    "credentials:Base": postgresql://${DB_USER:postgres}:${DB_PASSWORD:f3n3r}@${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:marketplace}